version: "3.8"

services:
  webhook:
    image: lwlook/webhook:latest
    command:
      - -verbose
      - -hooks=/hooks.json
      - -hotreload
    ports:
      - "9000:9000"
    configs:
      - source: hooks_json
        target: /hooks.json
      - source: run_gantry
        target: /run_gantry.sh
        mode: 0550
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gantry_test:/gantry_test
    environment:
      - "TRIGGER_FILE=/gantry_test/trigger"
      - "UPDATE_START=/gantry_test/start"
    deploy:
      placement:
        constraints:
          - node.role==manager

  gantry:
    image: shizunge/gantry:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gantry_test:/gantry_test
    environment:
      - "GANTRY_NODE_NAME={{.Node.Hostname}}"
      - "GANTRY_SLEEP_SECONDS=0"
      - "GANTRY_TRIGGER_PATH=/gantry_test/trigger"
      # Use a shared file /gantry_test/start to indicate that when we start a new update.
      # Also load parameters passed from webhook in /gantry_test/trigger.
      - "GANTRY_PRE_RUN_CMD=\
          date +%s > /gantry_test/start; \
          [ -f /gantry_test/trigger ] && source /gantry_test/trigger || touch /gantry_test/trigger; \
        "
    deploy:
      replicas: 1
      placement:
        # Running on the same node as webhook to access the shared volume.
        constraints:
          - node.role==manager
      restart_policy:
        condition: none
      labels:
        - webhook.run-gantry=true

configs:
  hooks_json:
    name: hooks_json
    file: ./hooks.json
  run_gantry:
    name: run_gantry
    file: ./run_gantry.sh

volumes:
  gantry_test:
    name: gantry_test