name: On pull request

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'src/*.sh'
      - 'tests/*.sh'
      - '.github/**'
  workflow_dispatch:
 
jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get install -y bash shellcheck
      - name: Analyse with shellcheck
        run: |
          set -e
          shellcheck -V
          shellcheck src/*.sh tests/*.sh
          set +e

  # Use a matrix to make it easier to find which test fails.
  test_scripts:
    name: Test scripts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_suit:
          - gantry_cleanup_images_spec.sh
          - gantry_common_options_spec.sh
          - gantry_filters_spec.sh
          - gantry_jobs_spec.sh
          - gantry_login_docker_config_spec.sh
          - gantry_login_negative_spec.sh
          - gantry_login_spec.sh
          - gantry_manifest_spec.sh
          - gantry_notify_spec.sh
          - gantry_parallel_spec.sh
          - gantry_rollback_spec.sh
          - gantry_service_multiple_spec.sh
          - gantry_service_no_running_tasks_spec.sh
          - gantry_service_single_spec.sh
          - gantry_update_options_spec.sh
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.0
      - name: Install shellspec
        run: |
          mkdir -p ~/shellspec
          cd ~/shellspec
          git clone https://github.com/shellspec/shellspec.git
          ln -s ~/shellspec/shellspec/shellspec /usr/local/bin/shellspec
          echo -n "shellspec version: "
          shellspec --version
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          bash shellspec --pattern tests/${{ matrix.test_suit }}

  test_scripts_parallel:
    name: Test scripts running in parallel
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.0
      - name: Install shellspec
        run: |
          mkdir -p ~/shellspec
          cd ~/shellspec
          git clone https://github.com/shellspec/shellspec.git
          ln -s ~/shellspec/shellspec/shellspec /usr/local/bin/shellspec
          echo -n "shellspec version: "
          shellspec --version
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run container tests
        run: |
          bash shellspec --jobs 50

  test_container:
    name: Test container
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.0
      - name: Install shellspec
        run: |
          mkdir -p ~/shellspec
          cd ~/shellspec
          git clone https://github.com/shellspec/shellspec.git
          ln -s ~/shellspec/shellspec/shellspec /usr/local/bin/shellspec
          echo -n "shellspec version: "
          shellspec --version
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run container tests
        run: |
          export GANTRY_TEST_CONTAINER=true
          export GANTRY_TEST_CONTAINER_REPO_TAG=
          echo "GANTRY_TEST_CONTAINER=${GANTRY_TEST_CONTAINER}"
          echo "GANTRY_TEST_CONTAINER_REPO_TAG=${GANTRY_TEST_CONTAINER_REPO_TAG}"
          bash shellspec --jobs 50
